(defun quater-turn (arr)
	(let* ((dim (array-dimension arr 0))
				 (ret (make-array (list dim dim))))
		(do ((r 0 (+ r 1)))
			((>= r dim) 'done)
			(do ((c 0 (+ c 1)))
				((>= c dim) 'done)
				(setf (aref ret c (- (- dim 1) r)) (aref arr r c))))
		ret))
